---
- hosts: webserver
  become: True
  tasks:
          - name: Install the Docker
            yum:
                    name: docker
                    state: present
          - name: start the docker service
            service:
                    name: docker
                    state: started
          - name: Install the apache server
            yum:
                    name: httpd
                    state: present
          - name: Start the apache server
            service:
                    name: httpd
                    state: started
...

